name: a15-6-6

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable(标准)
          - Dev(开发)
          - Other(其他/指定)
        default: Stable(标准)
      version:
        description: 'Custom kernel version name (Ex: Characters after 6.6.77-android15-8- or leave blank to use default kernel version uname)'
        required: false
        type: string
      build_time:
        description: 'Set Kernel Build Time'
        required: false
        type: string
      use_zram:
        description: 'Use ZRAM'
        required: true
        type: boolean
        default: true
      use_bbg:
        description: 'Use BBG (BaseBand Gruad)'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: 'Use KPM'
        required: true
        type: boolean
        default: true
      cancel_susfs:
        description: '取消susfs'
        required: true
        type: boolean
        default: false
      supp_op:
        description: 'Enable support for OnePlus 8E processor models? (No need to check this box if your device is not this model)'
        required: false
        type: boolean
        default: false
      get_manager:
        description: 'Build APP root + susfs'
        required: true
        type: boolean
        default: true
      onlyAk3:
        description: 'Upload only AK3 zip file? (No bootloader, faster download speed)'
        required: false
        type: boolean
        default: false


jobs:
  build-kernel-a15-6-6:
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      use_zram: ${{ inputs.use_zram }}
      use_bbg: ${{ inputs.use_bbg }}
      use_kpm: ${{ inputs.use_kpm }}
      cancel_susfs: ${{ inputs.cancel_susfs }}
      supp_op: ${{ inputs.supp_op }}
      onlyAk3: ${{ inputs.onlyAk3 }}
      build_time: ${{ inputs.build_time }}
  get-ksu-manager:
    if: ${{ inputs.get_manager }}
    uses: ./.github/workflows/get-manager.yml
    secrets: inherit
    with:
      kernelsu_variant: ${{ inputs.kernelsu_variant }}

